# -*- coding: utf-8 -*-
"""PRODUCTREVIEWSUMMARIZER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNiZViZ77j0q7fZ1S-4pU_qEI2ORJ8ks
"""

!pip install transformers torch

from transformers import pipeline
generator = pipeline(
     "text-generation",
     model = "gpt2"
 )
prompt = "Artificial Intelligence in Finance will"
result = generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated text:")
print(result[0]['generated_text'])