# -*- coding: utf-8 -*-
"""pros&cons.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XmngY0yU2Vwh-uMJhCga0pvVdoWW4zl
"""

!pip install sentence-transformers
from transformers import pipeline
import pandas as pd

from transformers import pipeline
sentiment = pipeline("sentiment-analysis")
reviews = """The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is Average and needs needs charging often.
The fan makes noise when many apps are running.
Overall,it is a good laptop for students but not for gaming.
"""
sentences = reviews.split(".")

pros = []
cons = []

for s in sentences:
    s = s.strip()
    if not s:
        continue

    result = sentiment(s)
    if not result:
        continue

    label = result[0]["label"]

    if label == "POSITIVE":
        pros.append(s)
    elif label == "NEGATIVE":
        cons.append(s)

print("Pros:", pros)
print("Cons:", cons)

pros = pros[:2]
cons = cons[:2]

df  = pd.DataFrame({
      "Pros": pros,
      "Cons": cons
  })
df