# -*- coding: utf-8 -*-
"""SentenceSimilarityProject.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lk0g8EsVmZ5TmPYrqqrjG_SqVIjpRt99
"""

!pip install transformers torch

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter Text 1: ")
text2 = input("Enter Text 2: ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1,embedding2)
print("\nSimilarity Score:",round(float(similarity), 2))
if similarity > 0.75:
  print("similarity level:High")
elif similarity > 0.4:
  print("Similarity level:Medium")
else:
  print("similarity level:Low")

