# -*- coding: utf-8 -*-
"""TIMETABLEGENERATOR.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqXDPegnUPtP1l5OABuJXvGx-KcH0mQ4
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

subjects_input = input("Enter subjects(comma seperated):")
days_input = input("Enter days(comma seperated):")
periods_per_day_input = input("Enter  number of periods per day:")

subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]
periods_per_day = int(periods_per_day_input)

if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
    print("Invalid input. Please try again.")
else:
  timetable = {}

  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)

  df = pd.DataFrame(timetable)
  df.index = [f"Period {i+1}" for i in range(periods_per_day)]

  print(df)

  df.to_csv("Timetable.csv")
  print("\nTimeTable saved as timetable.csv")

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

subjects_input = input("Enter subjects(comma seperated):")
days_input = input("Enter days(comma seperated):")
periods_per_day_input = input("Enter  number of periods per day:")

subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]
periods_per_day = int(periods_per_day_input)

if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
    print("Invalid input. Please try again.")
else:
  timetable = {}

  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)

  df = pd.DataFrame(timetable)
  df.index = [f"Period {i+1}" for i in range(periods_per_day)]

  print(df)

  df.to_csv("Timetable.csv")
  print("\nTimeTable saved as timetable.csv")